<div class="button btn bg-medium-blue text-white text-white-a text-white-force"></div>
<div class="border-b-4 border-b-[2px] border-b-[3px]"></div>
<div class="modal"><p>ok<a href="#">ok</a></p></div>
<div class="font-light !font-light"></div>
<i class="flaticon-twitter"></i>
<i class="flaticon-telegram -mt-10"></i>
<i class="flaticon-discord"></i>
<i class="flaticon-whatsapp"></i>
<i class="flaticon-instagram"></i>
<i class="flaticon-facebook"></i>
<i class="flaticon-facebook-app-symbol"></i>
<i class="flaticon-tiktok"></i>
<i class="flaticon-linkedin"></i>
<i class="flaticon-youtube"></i>
<i class="flaticon-messenger"></i>
<i class="flaticon-phone-call max-w-[1024px]"></i>
<i class="flaticon-mail"></i>
<i class="flaticon-maps-and-flags"></i>
<div class="!child-text-a-white"></div>
<div class="lg:grid-cols-1 lg:grid-cols-2 lg:grid-cols-3"></div>
<div class="lg:!mb-20 lg:mb-20 !mx-auto lg:columns-3 dropdown-icon right-[45px] z-[1000]"></div>
<i class="flaticon-printer"></i>
<i class="flaticon-right-chevron"></i>
<i class="flaticon-left-chevron"></i>
<i class="flaticon-down-chevron"></i>
<i class="flaticon-up-chevron"></i>
<i class="flaticon-down-arrow"></i>
<i class="flaticon-down-right-arrow"></i>
<i class="flaticon-left-arrow"></i>
<i class="flaticon-up-arrow"></i>
<i class="flaticon-up-left-arrow"></i>
<i class="flaticon-up-right-arrow"></i>
<i class="flaticon-floppy-disk"></i>
<i class="flaticon-user"></i>
<i class="flaticon-cancel"></i>
<i class="flaticon-close"></i>
<i class="flaticon-link"></i>
<i class="flaticon-down-arrow-1"></i>
<i class="flaticon-time"></i>
<ul class="custom-bullets custom-list mb-5 !mb-5 !mb-10 !mt-5 !mt-10 lg:columns-2 outer-pad outer-pad-x outer-pad-y lg:columns-2 mobile-only:py-5 mobile-only:mb-5 lg:outer-pad-y"></ul>
<div class="columns-2"></div>
<div class="at-top"></div>
<div class="scrolled-down"></div>
<div class="scrolling-up"></div>

<div class="duration-300 transition-all px-5 py-3 order-5"></div>
<div class="text-heading"></div>
<div class="relative mobile-only:flex mobile-only:justify-center mobile-only:-translate-y-[100%] mobile-only:overflow-y-auto"></div>
<div class="responsive-menu menu-list"></div>
<div class="text-left text-right text-center"></div>
<div class=" my-2 my-4 my-6 my-8 my-10 my-12 my-14 my-16 my-18 my-20 my-22 my-24 my-26 my-28 my-30 my-32  py-2 py-4 py-6 py-8 py-10 py-12 py-14 py-16 py-18 py-20 py-22 py-24 py-26 py-28 py-30 py-32"></div>
<div class=" mt-2 mt-4 mt-6 mt-8 mt-10 mt-12 mt-14 mt-16 mt-18 mt-20 mt-22 mt-24 mt-26 mt-28 mt-30 mt-32  pt-2 pt-4 pt-6 pt-8 pt-10 pt-12 pt-14 pt-16 pt-18 pt-20 pt-22 pt-24 pt-26 pt-28 pt-30 pt-32"></div>
<div class=" circle-icon mb-2 mb-4 mb-6 mb-8 mb-10 mb-12 mb-14 mb-16 mb-18 mb-20 mb-22 mb-24 mb-26 mb-28 mb-30 mb-32  pb-2 pb-4 pb-6 pb-8 pb-10 pb-12 pb-14 pb-16 pb-18 pb-20 pb-22 pb-24 pb-26 pb-28 pb-30 pb-32"></div>
<div class="flex flex-col justify-center"></div>
<div class=" flex  lg:flex  flex-row  flex-row-reverse  flex-col  flex-col-reverse   lg:flex-row  lg:flex-row-reverse  lg:flex-col  lg:flex-col-reverse  flex-wrap  flex-nowrap   lg:flex-wrap  lg:flex-nowrap  justify-start  justify-end  justify-center  justify-between  justify-around  justify-evenly   lg:justify-start  lg:justify-end  lg:justify-center  lg:justify-between  lg:justify-around  lg:justify-evenly "></div>

<div class="image-treatment-1"><div class="image"><img src="#"></div>
    <div class="img-treatment-1-child"><div></div></div>
    <div class="img-treatment-2-child mb-5"><div></div></div>
</div>
        <div class="custom-separator"></div>
        <div class="font-normal !font-normal"></div>
<div class="flex flex-col gap-5 rounded-[8px] border-2 border-primary px-10 py-5"></div>
        <div class="inset-container inset-container-tighter inset-container-tightest inset-container-tight"></div>
        <div class="inline-flex lg:inline-flex"></div>

        
        
        

                <div class="inline-flex lg:inline-flex"></div>
                <div class="py-0.5"></div>
                <div class="py-1"></div>
                <div class="py-1.5"></div>
                <div class="py-2"></div>
                <div class="py-2.5"></div>
                <div class="py-3"></div>
                <div class="py-3.5"></div>
                <div class="py-4"></div>
                <div class="py-5"></div>
                <div class="py-6"></div>
                <div class="py-7"></div>
                <div class="py-8"></div>
                <div class="py-9"></div>
                <div class="py-10"></div>
                <div class="py-11"></div>
                <div class="py-12"></div>
                <div class="py-14"></div>
                <div class="py-16"></div>
                <div class="py-20"></div>
                <div class="py-24"></div>
                <div class="py-28"></div>
                <div class="py-32"></div>
                <div class="py-36"></div>
                <div class="pt-0.5"></div>
                <div class="pt-1"></div>
                <div class="pt-1.5"></div>
                <div class="pt-2"></div>
                <div class="pt-2.5"></div>
                <div class="pt-3"></div>
                <div class="pt-3.5"></div>
                <div class="pt-4"></div>
                <div class="pt-5"></div>
                <div class="pt-6"></div>
                <div class="pt-7"></div>
                <div class="pt-8"></div>
                <div class="pt-9"></div>
                <div class="pt-10"></div>
                <div class="pt-11"></div>
                <div class="pt-12"></div>
                <div class="pt-14"></div>
                <div class="pt-16"></div>
                <div class="pt-20"></div>
                <div class="pt-24"></div>
                <div class="pt-28"></div>
                <div class="pt-32"></div>
                <div class="pt-36"></div>
                <div class="pb-0.5"></div>
                <div class="pb-1"></div>
                <div class="pb-1.5"></div>
                <div class="pb-2"></div>
                <div class="pb-2.5"></div>
                <div class="pb-3"></div>
                <div class="pb-3.5"></div>
                <div class="pb-4"></div>
                <div class="pb-5"></div>
                <div class="pb-6"></div>
                <div class="pb-7"></div>
                <div class="pb-8"></div>
                <div class="pb-9"></div>
                <div class="pb-10"></div>
                <div class="pb-11"></div>
                <div class="pb-12"></div>
                <div class="pb-14"></div>
                <div class="pb-16"></div>
                <div class="pb-20"></div>
                <div class="pb-24"></div>
                <div class="pb-28"></div>
                <div class="pb-32"></div>
                <div class="pb-36"></div>
                <div class="my-0.5"></div>
                <div class="my-1"></div>
                <div class="my-1.5"></div>
                <div class="my-2"></div>
                <div class="my-2.5"></div>
                <div class="my-3"></div>
                <div class="my-3.5"></div>
                <div class="my-4"></div>
                <div class="my-5"></div>
                <div class="my-6"></div>
                <div class="my-7"></div>
                <div class="my-8"></div>
                <div class="my-9"></div>
                <div class="my-10"></div>
                <div class="my-11"></div>
                <div class="my-12"></div>
                <div class="my-14"></div>
                <div class="my-16"></div>
                <div class="my-20"></div>
                <div class="my-24"></div>
                <div class="my-28"></div>
                <div class="my-32"></div>
                <div class="my-36"></div>
                <div class="mt-0.5"></div>
                <div class="mt-1"></div>
                <div class="mt-1.5"></div>
                <div class="mt-2"></div>
                <div class="mt-2.5"></div>
                <div class="mt-3"></div>
                <div class="mt-3.5"></div>
                <div class="mt-4"></div>
                <div class="mt-5"></div>
                <div class="mt-6"></div>
                <div class="mt-7"></div>
                <div class="mt-8"></div>
                <div class="mt-9"></div>
                <div class="mt-10"></div>
                <div class="mt-11"></div>
                <div class="mt-12"></div>
                <div class="mt-14"></div>
                <div class="mt-16"></div>
                <div class="mt-20"></div>
                <div class="mt-24"></div>
                <div class="mt-28"></div>
                <div class="mt-32"></div>
                <div class="mt-36"></div>
                <div class="mb-0.5"></div>
                <div class="mb-1"></div>
                <div class="mb-1.5"></div>
                <div class="mb-2"></div>
                <div class="mb-2.5"></div>
                <div class="mb-3"></div>
                <div class="mb-3.5"></div>
                <div class="mb-4"></div>
                <div class="mb-5"></div>
                <div class="mb-6"></div>
                <div class="mb-7"></div>
                <div class="mb-8"></div>
                <div class="mb-9"></div>
                <div class="mb-10"></div>
                <div class="mb-11"></div>
                <div class="mb-12"></div>
                <div class="mb-14"></div>
                <div class="mb-16"></div>
                <div class="mb-20"></div>
                <div class="mb-24"></div>
                <div class="mb-28"></div>
                <div class="mb-32"></div>
                <div class="mb-36"></div>
                <div class="lg:py-0.5"></div>
                <div class="lg:py-1"></div>
                <div class="lg:py-1.5"></div>
                <div class="lg:py-2"></div>
                <div class="lg:py-2.5"></div>
                <div class="lg:py-3"></div>
                <div class="lg:py-3.5"></div>
                <div class="lg:py-4"></div>
                <div class="lg:py-5"></div>
                <div class="lg:py-6"></div>
                <div class="lg:py-7"></div>
                <div class="lg:py-8"></div>
                <div class="lg:py-9"></div>
                <div class="lg:py-10"></div>
                <div class="lg:py-11"></div>
                <div class="lg:py-12"></div>
                <div class="lg:py-14"></div>
                <div class="lg:py-16"></div>
                <div class="lg:py-20"></div>
                <div class="lg:py-24"></div>
                <div class="lg:py-28"></div>
                <div class="lg:py-32"></div>
                <div class="lg:py-36"></div>
                <div class="lg:pt-0.5"></div>
                <div class="lg:pt-1"></div>
                <div class="lg:pt-1.5"></div>
                <div class="lg:pt-2"></div>
                <div class="lg:pt-2.5"></div>
                <div class="lg:pt-3"></div>
                <div class="lg:pt-3.5"></div>
                <div class="lg:pt-4"></div>
                <div class="lg:pt-5"></div>
                <div class="lg:pt-6"></div>
                <div class="lg:pt-7"></div>
                <div class="lg:pt-8"></div>
                <div class="lg:pt-9"></div>
                <div class="lg:pt-10"></div>
                <div class="lg:pt-11"></div>
                <div class="lg:pt-12"></div>
                <div class="lg:pt-14"></div>
                <div class="lg:pt-16"></div>
                <div class="lg:pt-20"></div>
                <div class="lg:pt-24"></div>
                <div class="lg:pt-28"></div>
                <div class="lg:pt-32"></div>
                <div class="lg:pt-36"></div>
                <div class="lg:pb-0.5"></div>
                <div class="lg:pb-1"></div>
                <div class="lg:pb-1.5"></div>
                <div class="lg:pb-2"></div>
                <div class="lg:pb-2.5"></div>
                <div class="lg:pb-3"></div>
                <div class="lg:pb-3.5"></div>
                <div class="lg:pb-4"></div>
                <div class="lg:pb-5"></div>
                <div class="lg:pb-6"></div>
                <div class="lg:pb-7"></div>
                <div class="lg:pb-8"></div>
                <div class="lg:pb-9"></div>
                <div class="lg:pb-10"></div>
                <div class="lg:pb-11"></div>
                <div class="lg:pb-12"></div>
                <div class="lg:pb-14"></div>
                <div class="lg:pb-16"></div>
                <div class="lg:pb-20"></div>
                <div class="lg:pb-24"></div>
                <div class="lg:pb-28"></div>
                <div class="lg:pb-32"></div>
                <div class="lg:pb-36"></div>
                <div class="lg:my-0.5"></div>
                <div class="lg:my-1"></div>
                <div class="lg:my-1.5"></div>
                <div class="lg:my-2"></div>
                <div class="lg:my-2.5"></div>
                <div class="lg:my-3"></div>
                <div class="lg:my-3.5"></div>
                <div class="lg:my-4"></div>
                <div class="lg:my-5"></div>
                <div class="lg:my-6"></div>
                <div class="lg:my-7"></div>
                <div class="lg:my-8"></div>
                <div class="lg:my-9"></div>
                <div class="lg:my-10"></div>
                <div class="lg:my-11"></div>
                <div class="lg:my-12"></div>
                <div class="lg:my-14"></div>
                <div class="lg:my-16"></div>
                <div class="lg:my-20"></div>
                <div class="lg:my-24"></div>
                <div class="lg:my-28"></div>
                <div class="lg:my-32"></div>
                <div class="lg:my-36"></div>
                <div class="lg:mt-0.5"></div>
                <div class="lg:mt-1"></div>
                <div class="lg:mt-1.5"></div>
                <div class="lg:mt-2"></div>
                <div class="lg:mt-2.5"></div>
                <div class="lg:mt-3"></div>
                <div class="lg:mt-3.5"></div>
                <div class="lg:mt-4"></div>
                <div class="lg:mt-5"></div>
                <div class="lg:mt-6"></div>
                <div class="lg:mt-7"></div>
                <div class="lg:mt-8"></div>
                <div class="lg:mt-9"></div>
                <div class="lg:mt-10"></div>
                <div class="lg:mt-11"></div>
                <div class="lg:mt-12"></div>
                <div class="lg:mt-14"></div>
                <div class="lg:mt-16"></div>
                <div class="lg:mt-20"></div>
                <div class="lg:mt-24"></div>
                <div class="lg:mt-28"></div>
                <div class="lg:mt-32"></div>
                <div class="lg:mt-36"></div>
                <div class="lg:mb-0.5"></div>
                <div class="lg:mb-1"></div>
                <div class="lg:mb-1.5"></div>
                <div class="lg:mb-2"></div>
                <div class="lg:mb-2.5"></div>
                <div class="lg:mb-3"></div>
                <div class="lg:mb-3.5"></div>
                <div class="lg:mb-4"></div>
                <div class="lg:mb-5"></div>
                <div class="lg:mb-6"></div>
                <div class="lg:mb-7"></div>
                <div class="lg:mb-8"></div>
                <div class="lg:mb-9"></div>
                <div class="lg:mb-10"></div>
                <div class="lg:mb-11"></div>
                <div class="lg:mb-12"></div>
                <div class="lg:mb-14"></div>
                <div class="lg:mb-16"></div>
                <div class="lg:mb-20"></div>
                <div class="lg:mb-24"></div>
                <div class="lg:mb-28"></div>
                <div class="lg:mb-32"></div>
                <div class="lg:mb-36"></div>

                <div class="grid grid-cols-1 grid-cols-2 grid-cols-3 grid-cols-4 lg:grid-cols-1 lg:grid-cols-2 lg:grid-cols-3 lg:grid-cols-4 "></div>

                <i class="flaticon-twitter"></i>
                <i class="flaticon-telegram"></i>
                <i class="flaticon-discord"></i>
                <i class="flaticon-whatsapp"></i>
                <i class="flaticon-instagram"></i>
                <i class="flaticon-facebook"></i>
                <i class="flaticon-facebook-app-symbol"></i>
                <i class="flaticon-tiktok"></i>
                <i class="flaticon-linkedin"></i>
                <i class="flaticon-youtube"></i>
                <i class="flaticon-messenger"></i>
                <div class="items-start"></div>
                <div class="items-end"></div>
                <div class="items-center"></div>
                <div class="items-baseline"></div>
                <div class="items-stretch"></div>
                <div class="items-start"></div>
                <div class="items-end"></div>
                <div class="items-center"></div>
                <div class="items-baseline"></div>
                <div class="items-stretch"></div>
                <div class="max-w-[10%]"></div>
                <div class="max-w-[20%]"></div>
                <div class="max-w-[30%]"></div>
                <div class="max-w-[40%]"></div>
                <div class="max-w-[50%]"></div>
                <div class="max-w-[60%]"></div>
                <div class="max-w-[70%]"></div>
                <div class="max-w-[80%]"></div>
                <div class="lg:shadow-2xl mobile-only:mx-[20%] mobile-only:mt-10 border-b-2 border-secondary max-w-[90%]"></div>
                <div class="max-w-[100%]"></div>
                <div class="lg:max-w-[10%]"></div>
                <div class="lg:max-w-[20%]"></div>
                <div class="lg:max-w-[30%]"></div>
                <div class="lg:max-w-[40%]"></div>
                <div class="lg:max-w-[50%]"></div>
                <div class="lg:max-w-[60%]"></div>
                <div class="lg:max-w-[70%]"></div>
                <div class="lg:max-w-[80%]"></div>
                <div class="lg:max-w-[90%]"></div>
                <div class="lg:max-w-[100%]"></div>
                <div class="lg:min-h-[10vh]"></div>
                <div class="lg:min-h-[20vh]"></div>
                <div class="lg:min-h-[30vh]"></div>
                <div class="lg:min-h-[40vh]"></div>
                <div class="lg:min-h-[50vh]"></div>
                <div class="lg:min-h-[60vh]"></div>
                <div class="lg:min-h-[70vh]"></div>
                <div class="lg:min-h-[80vh]"></div>
                <div class="lg:min-h-[90vh]"></div>
                <div class="lg:min-h-[100vh]"></div>
                <div class="min-h-[10vh]"></div>
                <div class="min-h-[20vh]"></div>
                <div class="min-h-[30vh]"></div>
                <div class="min-h-[40vh]"></div>
                <div class="min-h-[50vh]"></div>
                <div class="min-h-[60vh]"></div>
                <div class="min-h-[70vh]"></div>
                <div class="min-h-[80vh]"></div>
<div class="lg:h-[10vh]"></div>
<div class="lg:h-[20vh]"></div>
<div class="lg:h-[30vh]"></div>
<div class="lg:h-[40vh]"></div>
<div class="lg:h-[50vh]"></div>
<div class="lg:h-[60vh]"></div>
<div class="lg:h-[70vh]"></div>
<div class="lg:h-[80vh]"></div>
<div class="lg:h-[90vh]"></div>
<div class="lg:h-[100vh]"></div>
<div class="h-[10vh]"></div>
<div class="h-[20vh]"></div>
<div class="h-[30vh]"></div>
<div class="h-[40vh]"></div>
<div class="h-[50vh]"></div>
<div class="h-[60vh]"></div>
<div class="h-[70vh]"></div>
<div class="h-[80vh]"></div>
<div class="h-[90vh]"></div>
<div class="h-[100vh]"></div>
<div class="menu-list mobile-active"></div>
                <div class="min-h-[90vh]"></div>
                <div class="min-h-[100vh]"></div>
<div class=" hover:bg-primary custom-transition leading-[150%] leading-[125%] !mx-0 !px-0"></div>

<div class="outer-pad-extra hours separator-before lg:before:hidden"></div>
                <div class="bg-cover bg-contain lg:bg-cover lg:bg-contain"></div>
                <div class="bg-repeat bg-no-repeat"></div><div class="font-inter"></div><div class="font-roboto"></div><div class="bg-body-background"></div><div class="border-t-body-background"></div><div class="border-b-body-background"></div><div class="border-l-body-background"></div><div class="border-r-body-background"></div><div class="border-body-background"></div><div class="text-body-background"></div><div class="lg:bg-body-background"></div><div class="hover:bg-body-background"></div><div class="hover:text-body-background"></div><div class="hover:!text-body-background"></div><div class="hover:!bg-body-background"></div><div class="!text-body-background"></div><div class="!bg-body-background"></div><div class="bg-body-text"></div><div class="border-t-body-text"></div><div class="border-b-body-text"></div><div class="border-l-body-text"></div><div class="border-r-body-text"></div><div class="border-body-text"></div><div class="text-body-text"></div><div class="lg:bg-body-text"></div><div class="hover:bg-body-text"></div><div class="hover:text-body-text"></div><div class="hover:!text-body-text"></div><div class="hover:!bg-body-text"></div><div class="!text-body-text"></div><div class="!bg-body-text"></div><div class="bg-primary"></div><div class="border-t-primary"></div><div class="border-b-primary"></div><div class="border-l-primary"></div><div class="border-r-primary"></div><div class="border-primary"></div><div class="text-primary"></div><div class="lg:bg-primary"></div><div class="hover:bg-primary"></div><div class="hover:text-primary"></div><div class="hover:!text-primary"></div><div class="hover:!bg-primary"></div><div class="!text-primary"></div><div class="!bg-primary"></div><div class="bg-secondary"></div><div class="border-t-secondary"></div><div class="border-b-secondary"></div><div class="border-l-secondary"></div><div class="border-r-secondary"></div><div class="border-secondary"></div><div class="text-secondary"></div><div class="lg:bg-secondary"></div><div class="hover:bg-secondary"></div><div class="hover:text-secondary"></div><div class="hover:!text-secondary"></div><div class="hover:!bg-secondary"></div><div class="!text-secondary"></div><div class="!bg-secondary"></div><div class="bg-accent"></div><div class="border-t-accent"></div><div class="border-b-accent"></div><div class="border-l-accent"></div><div class="border-r-accent"></div><div class="border-accent"></div><div class="text-accent"></div><div class="lg:bg-accent"></div><div class="hover:bg-accent"></div><div class="hover:text-accent"></div><div class="hover:!text-accent"></div><div class="hover:!bg-accent"></div><div class="!text-accent"></div><div class="!bg-accent"></div>

<div class="text-body-text-a"><a href="#"></a></div>
<div class="text-white-a"><a href="#"></a></div>
<div class="offset-shape font-heading font-inter"></div>
<div class="[&_ul]:lg:flex lg:[&_ul]:flex mobile-only:!translate-y-0"></div>