name: PHPCS check
on:
  pull_request:
    branches:
      - main
      - staging

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.3"
          ini-values: "memory_limit=1G"
          coverage: none
          tools: cs2pr
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"
      - name: Run PHPCS checks
        continue-on-error: true
        run: vendor/bin/phpcs ./web/wp-content/themes/starter-2024/ --standard=statenweb.xml -d memory_limit=512M --ignore=*.js,./web/wp-content/themes/starter-2024/vendor/*,./web/wp-content/themes/starter-2024/node_modules/*,*.css --error-severity=1 --warning-severity=6 --report-full --report-checkstyle=./phpcs-report.xml
      - name: Show PHPCS results in PR
        run: cs2pr ./phpcs-report.xml
